import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/app/modules/Header";
import { Footer } from "./modules/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className="bg-grey">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
